#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  
  # Newline = true only works for the first block, but if it's empty it doesn't work at all
  [[blocks.segments]]
    alias = 'BlankLine'
    type = 'text'
    style = 'plain'
    template = """ """

  [[blocks.segments]]
    alias = 'ExecutionTime'
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = """  {{ .FormattedMs }}
"""

    [blocks.segments.properties]
      threshold = 1500

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    # Visible when user is root/elevated shell
    type = 'root'
    style = 'plain'
    template = '[root] <#aaa>in</> '
    background = ''
    foreground = '#E06C75'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    alias = 'Path'
    type = 'path'
    style = 'plain'
    template = '{{ .Path }} '
    background = ''
    foreground = '#4ca4ff'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    # Display git context
    type = 'git'
    style = 'plain'
    template = '<#aaa>on</> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    background = ''
    foreground = '#ef5cf8'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      fetch_status = true

  [[blocks.segments]]
    # Display node version when in node project
    type = 'node'
    style = 'plain'
    template = '<#aaa>via</>  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
    background = ''
    foreground = '#00c471'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      fetch_version = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  # Vi mode indicator
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground = '#FF79C6'
    template = '[{{ .Env.VIM_MODE }}] '

  [[blocks.segments]]
    # Text entry
    type = 'text'
    style = 'plain'
    foreground = '#63F08C'
    template = '➜ '
    background = 'transparent'


[transient_prompt]
  background = "transparent"
  template = """{{ if .Segments.ExecutionTime.FormattedMs}} <#999> {{ .Segments.ExecutionTime.FormattedMs }}</>
{{end}}
 <#FF79C6>➜</> """

[secondary_prompt]
  foreground = '#888'
  template = '➜➜'

[palette]
  error = "#C94A16"
