return {
  misc = {
    dots = "󰇘",
  },
  ft = {
    octo = "",
  },
  ---@type { icon: string, textHl: string, lineHl?: string }
  dap = {
    Breakpoint = { " ", "DapBreakpoint" },
    BreakpointCondition = { " ", "DapBreakpointCondition" },
    BreakpointRejected = { " ", "DapBreakpointRejected" },
    Stopped = { "󰁕 ", "DapStopped", "DapStoppedLine" },
    LogPoint = { ".>", "DiagnosticInfo" },
  },
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
  kinds = {
    Array = " ",
    Avante = "🧠",
    Boolean = "󰨙 ",
    Class = " ",
    Codeium = "🤖",
    Color = " ",
    Control = " ",
    Collapsed = " ",
    Constant = "󰏿 ",
    Constructor = " ",
    Copilot = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = "󰊕 ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = "󰊕 ",
    Module = " ",
    Namespace = "󰦮 ",
    Null = " ",
    Number = "󰎠 ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = "󱄽 ",
    String = " ",
    Struct = "󰆼 ",
    Supermaven = "🦸",
    TabNine = "󰏚 ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = "󰀫 ",
  },
}
