# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

disableStartupPopups: true

gui:
  nerdFontsVersion: "3"
  skipStashWarning: true
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  timeFormat: 2024-10-24
  shortTimeFormat: 18:22
  commandLogSize: 5
  filterMode: fuzzy
  spinner:
    rate: 50
    frames:
      - "◜"
      - "◠"
      - "◝"
      - "◞"
      - "◡"
      - "◟"
  statusPanelView: allBranchesLog

git:
  disableForcePushing: true

# promptToReturnFromSubprocess: false

# TODO: Disable tab/shift tab to cycle module.
keybinding:
  universal:
    # I often do this by accident and it risks "loosing" commits from working copy of branch.
    # If this isn't noticed its a pain to restore later
    pullFiles: <disabled>
    # This opens on <c-p> which I find annoying since I also use that to page
    createPatchOptionsMenu: <disabled>

    prevBlock: <disabled>
    nextBlock: <disabled>
    prevBlock-alt: <disabled>
    nextBlock-alt: <disabled>
    prevBlock-alt2: <disabled>
    nextBlock-alt2: <disabled>

    prevTab: h
    nextTab: l
